# Generated by Django 4.2.6 on 2023-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('add', models.TextField()),
            ],
        ),
    ]
