# Generated by Django 4.2.6 on 2023-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='add',
            field=models.CharField(max_length=50),
        ),
    ]
